spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: fraud-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.consumer.kafkaconsumer.Model.TransactionEvent

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

    listener:
      ack-mode: manual

  data:
    redis:
      host: localhost
      port: 6379

  fraud:
    threshold: 3
    window-ms: 10000